fragment ProjectParts on Project {
  __typename
  title
  slug
  category
  image
  year
  order
  featuredOnHome
  description
  fullDescription
  gallery
  siteUrl
}

fragment SiteSettingsParts on SiteSettings {
  __typename
  email
  phone
  phoneLink
  address
  copyright
  contactHeadingLine1
  contactHeadingLine2
  scrollText
  socials {
    __typename
    name
    url
    openInNewTab
  }
  footerLinks {
    __typename
    label
    url
  }
}

fragment PartnersParts on Partners {
  __typename
  partnersLabel
  partners {
    __typename
    name
    url
  }
}

fragment HomePageParts on HomePage {
  __typename
  heroLabel
  heroTitleLine1
  heroTitleLine2
  heroDescription
  aboutHeading
  aboutParagraph1
  aboutParagraph2
  servicesHeading
  servicesSubtext
  servicesButtonText
  services {
    __typename
    id
    title
    description
  }
  processHeading
  processSubtext
  processSteps {
    __typename
    num
    title
    description
    tags
  }
}

fragment AboutPageParts on AboutPage {
  __typename
  heroLabel
  heroTitleLine1
  heroTitleLine2
  studioImage
  studioImageAlt
  introHeading
  introParagraph1
  introParagraph2
  valuesLabel
  valuesHeading
  values {
    __typename
    id
    title
    description
  }
  teamMembers {
    __typename
    name
    role
    image
    bio
    order
  }
}

fragment ServicesPageParts on ServicesPage {
  __typename
  heroLabel
  heroTitleLine1
  heroTitleLine2
  categories {
    __typename
    category
    description
    items
  }
}

fragment ContactPageParts on ContactPage {
  __typename
  heroLabel
  heroTitleLine1
  heroTitleLine2
  heroTitlePunctuation
  heroDescription
  trustIndicators {
    __typename
    icon
    title
    description
  }
}
