//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  project: Project;
  projectConnection: ProjectConnection;
  teamMember: TeamMember;
  teamMemberConnection: TeamMemberConnection;
  siteSettings: SiteSettings;
  siteSettingsConnection: SiteSettingsConnection;
  partners: Partners;
  partnersConnection: PartnersConnection;
  homePage: HomePage;
  homePageConnection: HomePageConnection;
  aboutPage: AboutPage;
  aboutPageConnection: AboutPageConnection;
  servicesPage: ServicesPage;
  servicesPageConnection: ServicesPageConnection;
  contactPage: ContactPage;
  contactPageConnection: ContactPageConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjectArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjectConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectFilter>;
};


export type QueryTeamMemberArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTeamMemberConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamMemberFilter>;
};


export type QuerySiteSettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteSettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteSettingsFilter>;
};


export type QueryPartnersArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPartnersConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PartnersFilter>;
};


export type QueryHomePageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomePageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomePageFilter>;
};


export type QueryAboutPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutPageFilter>;
};


export type QueryServicesPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServicesPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServicesPageFilter>;
};


export type QueryContactPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactPageFilter>;
};

export type DocumentFilter = {
  project?: InputMaybe<ProjectFilter>;
  teamMember?: InputMaybe<TeamMemberFilter>;
  siteSettings?: InputMaybe<SiteSettingsFilter>;
  partners?: InputMaybe<PartnersFilter>;
  homePage?: InputMaybe<HomePageFilter>;
  aboutPage?: InputMaybe<AboutPageFilter>;
  servicesPage?: InputMaybe<ServicesPageFilter>;
  contactPage?: InputMaybe<ContactPageFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Project | TeamMember | SiteSettings | Partners | HomePage | AboutPage | ServicesPage | ContactPage | Folder;

export type Project = Node & Document & {
  __typename?: 'Project';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  category: Scalars['String']['output'];
  image?: Maybe<Scalars['String']['output']>;
  year: Scalars['String']['output'];
  order?: Maybe<Scalars['Float']['output']>;
  description: Scalars['String']['output'];
  fullDescription?: Maybe<Scalars['String']['output']>;
  gallery?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type ProjectFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  year?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  description?: InputMaybe<StringFilter>;
  fullDescription?: InputMaybe<StringFilter>;
  gallery?: InputMaybe<ImageFilter>;
};

export type ProjectConnectionEdges = {
  __typename?: 'ProjectConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Project>;
};

export type ProjectConnection = Connection & {
  __typename?: 'ProjectConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProjectConnectionEdges>>>;
};

export type TeamMember = Node & Document & {
  __typename?: 'TeamMember';
  name: Scalars['String']['output'];
  role: Scalars['String']['output'];
  image?: Maybe<Scalars['String']['output']>;
  bio?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TeamMemberFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  image?: InputMaybe<ImageFilter>;
  bio?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type TeamMemberConnectionEdges = {
  __typename?: 'TeamMemberConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<TeamMember>;
};

export type TeamMemberConnection = Connection & {
  __typename?: 'TeamMemberConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TeamMemberConnectionEdges>>>;
};

export type SiteSettingsSocials = {
  __typename?: 'SiteSettingsSocials';
  name: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type SiteSettingsFooterLinks = {
  __typename?: 'SiteSettingsFooterLinks';
  label: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type SiteSettings = Node & Document & {
  __typename?: 'SiteSettings';
  email: Scalars['String']['output'];
  phone: Scalars['String']['output'];
  phoneLink?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  copyright?: Maybe<Scalars['String']['output']>;
  contactHeadingLine1?: Maybe<Scalars['String']['output']>;
  contactHeadingLine2?: Maybe<Scalars['String']['output']>;
  scrollText?: Maybe<Scalars['String']['output']>;
  socials?: Maybe<Array<Maybe<SiteSettingsSocials>>>;
  footerLinks?: Maybe<Array<Maybe<SiteSettingsFooterLinks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SiteSettingsSocialsFilter = {
  name?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type SiteSettingsFooterLinksFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type SiteSettingsFilter = {
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  phoneLink?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  copyright?: InputMaybe<StringFilter>;
  contactHeadingLine1?: InputMaybe<StringFilter>;
  contactHeadingLine2?: InputMaybe<StringFilter>;
  scrollText?: InputMaybe<StringFilter>;
  socials?: InputMaybe<SiteSettingsSocialsFilter>;
  footerLinks?: InputMaybe<SiteSettingsFooterLinksFilter>;
};

export type SiteSettingsConnectionEdges = {
  __typename?: 'SiteSettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SiteSettings>;
};

export type SiteSettingsConnection = Connection & {
  __typename?: 'SiteSettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteSettingsConnectionEdges>>>;
};

export type Partners = Node & Document & {
  __typename?: 'Partners';
  partnersLabel: Scalars['String']['output'];
  partners?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PartnersFilter = {
  partnersLabel?: InputMaybe<StringFilter>;
  partners?: InputMaybe<StringFilter>;
};

export type PartnersConnectionEdges = {
  __typename?: 'PartnersConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Partners>;
};

export type PartnersConnection = Connection & {
  __typename?: 'PartnersConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PartnersConnectionEdges>>>;
};

export type HomePageServices = {
  __typename?: 'HomePageServices';
  id?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
};

export type HomePageProcessSteps = {
  __typename?: 'HomePageProcessSteps';
  num?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type HomePage = Node & Document & {
  __typename?: 'HomePage';
  heroLabel: Scalars['String']['output'];
  heroTitleLine1?: Maybe<Scalars['String']['output']>;
  heroTitleLine2?: Maybe<Scalars['String']['output']>;
  heroDescription?: Maybe<Scalars['String']['output']>;
  aboutHeading?: Maybe<Scalars['String']['output']>;
  aboutParagraph1?: Maybe<Scalars['String']['output']>;
  aboutParagraph2?: Maybe<Scalars['String']['output']>;
  servicesHeading?: Maybe<Scalars['String']['output']>;
  servicesSubtext?: Maybe<Scalars['String']['output']>;
  servicesButtonText?: Maybe<Scalars['String']['output']>;
  services?: Maybe<Array<Maybe<HomePageServices>>>;
  processHeading?: Maybe<Scalars['String']['output']>;
  processSubtext?: Maybe<Scalars['String']['output']>;
  processSteps?: Maybe<Array<Maybe<HomePageProcessSteps>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomePageServicesFilter = {
  id?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type HomePageProcessStepsFilter = {
  num?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
};

export type HomePageFilter = {
  heroLabel?: InputMaybe<StringFilter>;
  heroTitleLine1?: InputMaybe<StringFilter>;
  heroTitleLine2?: InputMaybe<StringFilter>;
  heroDescription?: InputMaybe<StringFilter>;
  aboutHeading?: InputMaybe<StringFilter>;
  aboutParagraph1?: InputMaybe<StringFilter>;
  aboutParagraph2?: InputMaybe<StringFilter>;
  servicesHeading?: InputMaybe<StringFilter>;
  servicesSubtext?: InputMaybe<StringFilter>;
  servicesButtonText?: InputMaybe<StringFilter>;
  services?: InputMaybe<HomePageServicesFilter>;
  processHeading?: InputMaybe<StringFilter>;
  processSubtext?: InputMaybe<StringFilter>;
  processSteps?: InputMaybe<HomePageProcessStepsFilter>;
};

export type HomePageConnectionEdges = {
  __typename?: 'HomePageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<HomePage>;
};

export type HomePageConnection = Connection & {
  __typename?: 'HomePageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomePageConnectionEdges>>>;
};

export type AboutPageValues = {
  __typename?: 'AboutPageValues';
  id?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
};

export type AboutPage = Node & Document & {
  __typename?: 'AboutPage';
  heroLabel: Scalars['String']['output'];
  heroTitleLine1?: Maybe<Scalars['String']['output']>;
  heroTitleLine2?: Maybe<Scalars['String']['output']>;
  studioImage?: Maybe<Scalars['String']['output']>;
  studioImageAlt?: Maybe<Scalars['String']['output']>;
  introHeading?: Maybe<Scalars['String']['output']>;
  introParagraph1?: Maybe<Scalars['String']['output']>;
  introParagraph2?: Maybe<Scalars['String']['output']>;
  valuesLabel?: Maybe<Scalars['String']['output']>;
  valuesHeading?: Maybe<Scalars['String']['output']>;
  values?: Maybe<Array<Maybe<AboutPageValues>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AboutPageValuesFilter = {
  id?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type AboutPageFilter = {
  heroLabel?: InputMaybe<StringFilter>;
  heroTitleLine1?: InputMaybe<StringFilter>;
  heroTitleLine2?: InputMaybe<StringFilter>;
  studioImage?: InputMaybe<ImageFilter>;
  studioImageAlt?: InputMaybe<StringFilter>;
  introHeading?: InputMaybe<StringFilter>;
  introParagraph1?: InputMaybe<StringFilter>;
  introParagraph2?: InputMaybe<StringFilter>;
  valuesLabel?: InputMaybe<StringFilter>;
  valuesHeading?: InputMaybe<StringFilter>;
  values?: InputMaybe<AboutPageValuesFilter>;
};

export type AboutPageConnectionEdges = {
  __typename?: 'AboutPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<AboutPage>;
};

export type AboutPageConnection = Connection & {
  __typename?: 'AboutPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AboutPageConnectionEdges>>>;
};

export type ServicesPageCategories = {
  __typename?: 'ServicesPageCategories';
  category: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type ServicesPage = Node & Document & {
  __typename?: 'ServicesPage';
  heroLabel: Scalars['String']['output'];
  heroTitleLine1?: Maybe<Scalars['String']['output']>;
  heroTitleLine2?: Maybe<Scalars['String']['output']>;
  categories?: Maybe<Array<Maybe<ServicesPageCategories>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ServicesPageCategoriesFilter = {
  category?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  items?: InputMaybe<StringFilter>;
};

export type ServicesPageFilter = {
  heroLabel?: InputMaybe<StringFilter>;
  heroTitleLine1?: InputMaybe<StringFilter>;
  heroTitleLine2?: InputMaybe<StringFilter>;
  categories?: InputMaybe<ServicesPageCategoriesFilter>;
};

export type ServicesPageConnectionEdges = {
  __typename?: 'ServicesPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ServicesPage>;
};

export type ServicesPageConnection = Connection & {
  __typename?: 'ServicesPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServicesPageConnectionEdges>>>;
};

export type ContactPageTrustIndicators = {
  __typename?: 'ContactPageTrustIndicators';
  icon?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
};

export type ContactPage = Node & Document & {
  __typename?: 'ContactPage';
  heroLabel: Scalars['String']['output'];
  heroTitleLine1?: Maybe<Scalars['String']['output']>;
  heroTitleLine2?: Maybe<Scalars['String']['output']>;
  heroTitlePunctuation?: Maybe<Scalars['String']['output']>;
  heroDescription?: Maybe<Scalars['String']['output']>;
  trustIndicators?: Maybe<Array<Maybe<ContactPageTrustIndicators>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactPageTrustIndicatorsFilter = {
  icon?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type ContactPageFilter = {
  heroLabel?: InputMaybe<StringFilter>;
  heroTitleLine1?: InputMaybe<StringFilter>;
  heroTitleLine2?: InputMaybe<StringFilter>;
  heroTitlePunctuation?: InputMaybe<StringFilter>;
  heroDescription?: InputMaybe<StringFilter>;
  trustIndicators?: InputMaybe<ContactPageTrustIndicatorsFilter>;
};

export type ContactPageConnectionEdges = {
  __typename?: 'ContactPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ContactPage>;
};

export type ContactPageConnection = Connection & {
  __typename?: 'ContactPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactPageConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateProject: Project;
  createProject: Project;
  updateTeamMember: TeamMember;
  createTeamMember: TeamMember;
  updateSiteSettings: SiteSettings;
  createSiteSettings: SiteSettings;
  updatePartners: Partners;
  createPartners: Partners;
  updateHomePage: HomePage;
  createHomePage: HomePage;
  updateAboutPage: AboutPage;
  createAboutPage: AboutPage;
  updateServicesPage: ServicesPage;
  createServicesPage: ServicesPage;
  updateContactPage: ContactPage;
  createContactPage: ContactPage;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectMutation;
};


export type MutationCreateProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectMutation;
};


export type MutationUpdateTeamMemberArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMemberMutation;
};


export type MutationCreateTeamMemberArgs = {
  relativePath: Scalars['String']['input'];
  params: TeamMemberMutation;
};


export type MutationUpdateSiteSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteSettingsMutation;
};


export type MutationCreateSiteSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteSettingsMutation;
};


export type MutationUpdatePartnersArgs = {
  relativePath: Scalars['String']['input'];
  params: PartnersMutation;
};


export type MutationCreatePartnersArgs = {
  relativePath: Scalars['String']['input'];
  params: PartnersMutation;
};


export type MutationUpdateHomePageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomePageMutation;
};


export type MutationCreateHomePageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomePageMutation;
};


export type MutationUpdateAboutPageArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutPageMutation;
};


export type MutationCreateAboutPageArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutPageMutation;
};


export type MutationUpdateServicesPageArgs = {
  relativePath: Scalars['String']['input'];
  params: ServicesPageMutation;
};


export type MutationCreateServicesPageArgs = {
  relativePath: Scalars['String']['input'];
  params: ServicesPageMutation;
};


export type MutationUpdateContactPageArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactPageMutation;
};


export type MutationCreateContactPageArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactPageMutation;
};

export type DocumentUpdateMutation = {
  project?: InputMaybe<ProjectMutation>;
  teamMember?: InputMaybe<TeamMemberMutation>;
  siteSettings?: InputMaybe<SiteSettingsMutation>;
  partners?: InputMaybe<PartnersMutation>;
  homePage?: InputMaybe<HomePageMutation>;
  aboutPage?: InputMaybe<AboutPageMutation>;
  servicesPage?: InputMaybe<ServicesPageMutation>;
  contactPage?: InputMaybe<ContactPageMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  project?: InputMaybe<ProjectMutation>;
  teamMember?: InputMaybe<TeamMemberMutation>;
  siteSettings?: InputMaybe<SiteSettingsMutation>;
  partners?: InputMaybe<PartnersMutation>;
  homePage?: InputMaybe<HomePageMutation>;
  aboutPage?: InputMaybe<AboutPageMutation>;
  servicesPage?: InputMaybe<ServicesPageMutation>;
  contactPage?: InputMaybe<ContactPageMutation>;
};

export type ProjectMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  fullDescription?: InputMaybe<Scalars['String']['input']>;
  gallery?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type TeamMemberMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type SiteSettingsSocialsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSettingsFooterLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSettingsMutation = {
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  phoneLink?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  copyright?: InputMaybe<Scalars['String']['input']>;
  contactHeadingLine1?: InputMaybe<Scalars['String']['input']>;
  contactHeadingLine2?: InputMaybe<Scalars['String']['input']>;
  scrollText?: InputMaybe<Scalars['String']['input']>;
  socials?: InputMaybe<Array<InputMaybe<SiteSettingsSocialsMutation>>>;
  footerLinks?: InputMaybe<Array<InputMaybe<SiteSettingsFooterLinksMutation>>>;
};

export type PartnersMutation = {
  partnersLabel?: InputMaybe<Scalars['String']['input']>;
  partners?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomePageServicesMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type HomePageProcessStepsMutation = {
  num?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomePageMutation = {
  heroLabel?: InputMaybe<Scalars['String']['input']>;
  heroTitleLine1?: InputMaybe<Scalars['String']['input']>;
  heroTitleLine2?: InputMaybe<Scalars['String']['input']>;
  heroDescription?: InputMaybe<Scalars['String']['input']>;
  aboutHeading?: InputMaybe<Scalars['String']['input']>;
  aboutParagraph1?: InputMaybe<Scalars['String']['input']>;
  aboutParagraph2?: InputMaybe<Scalars['String']['input']>;
  servicesHeading?: InputMaybe<Scalars['String']['input']>;
  servicesSubtext?: InputMaybe<Scalars['String']['input']>;
  servicesButtonText?: InputMaybe<Scalars['String']['input']>;
  services?: InputMaybe<Array<InputMaybe<HomePageServicesMutation>>>;
  processHeading?: InputMaybe<Scalars['String']['input']>;
  processSubtext?: InputMaybe<Scalars['String']['input']>;
  processSteps?: InputMaybe<Array<InputMaybe<HomePageProcessStepsMutation>>>;
};

export type AboutPageValuesMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type AboutPageMutation = {
  heroLabel?: InputMaybe<Scalars['String']['input']>;
  heroTitleLine1?: InputMaybe<Scalars['String']['input']>;
  heroTitleLine2?: InputMaybe<Scalars['String']['input']>;
  studioImage?: InputMaybe<Scalars['String']['input']>;
  studioImageAlt?: InputMaybe<Scalars['String']['input']>;
  introHeading?: InputMaybe<Scalars['String']['input']>;
  introParagraph1?: InputMaybe<Scalars['String']['input']>;
  introParagraph2?: InputMaybe<Scalars['String']['input']>;
  valuesLabel?: InputMaybe<Scalars['String']['input']>;
  valuesHeading?: InputMaybe<Scalars['String']['input']>;
  values?: InputMaybe<Array<InputMaybe<AboutPageValuesMutation>>>;
};

export type ServicesPageCategoriesMutation = {
  category?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ServicesPageMutation = {
  heroLabel?: InputMaybe<Scalars['String']['input']>;
  heroTitleLine1?: InputMaybe<Scalars['String']['input']>;
  heroTitleLine2?: InputMaybe<Scalars['String']['input']>;
  categories?: InputMaybe<Array<InputMaybe<ServicesPageCategoriesMutation>>>;
};

export type ContactPageTrustIndicatorsMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type ContactPageMutation = {
  heroLabel?: InputMaybe<Scalars['String']['input']>;
  heroTitleLine1?: InputMaybe<Scalars['String']['input']>;
  heroTitleLine2?: InputMaybe<Scalars['String']['input']>;
  heroTitlePunctuation?: InputMaybe<Scalars['String']['input']>;
  heroDescription?: InputMaybe<Scalars['String']['input']>;
  trustIndicators?: InputMaybe<Array<InputMaybe<ContactPageTrustIndicatorsMutation>>>;
};

export type ProjectPartsFragment = { __typename: 'Project', title: string, slug: string, category: string, image?: string | null, year: string, order?: number | null, description: string, fullDescription?: string | null, gallery?: Array<string | null> | null };

export type TeamMemberPartsFragment = { __typename: 'TeamMember', name: string, role: string, image?: string | null, bio?: string | null, order?: number | null };

export type SiteSettingsPartsFragment = { __typename: 'SiteSettings', email: string, phone: string, phoneLink?: string | null, address?: string | null, copyright?: string | null, contactHeadingLine1?: string | null, contactHeadingLine2?: string | null, scrollText?: string | null, socials?: Array<{ __typename: 'SiteSettingsSocials', name: string, url: string } | null> | null, footerLinks?: Array<{ __typename: 'SiteSettingsFooterLinks', label: string, url: string } | null> | null };

export type PartnersPartsFragment = { __typename: 'Partners', partnersLabel: string, partners?: Array<string | null> | null };

export type HomePagePartsFragment = { __typename: 'HomePage', heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, heroDescription?: string | null, aboutHeading?: string | null, aboutParagraph1?: string | null, aboutParagraph2?: string | null, servicesHeading?: string | null, servicesSubtext?: string | null, servicesButtonText?: string | null, processHeading?: string | null, processSubtext?: string | null, services?: Array<{ __typename: 'HomePageServices', id?: string | null, title: string, description?: string | null } | null> | null, processSteps?: Array<{ __typename: 'HomePageProcessSteps', num?: string | null, title: string, description?: string | null, tags?: Array<string | null> | null } | null> | null };

export type AboutPagePartsFragment = { __typename: 'AboutPage', heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, studioImage?: string | null, studioImageAlt?: string | null, introHeading?: string | null, introParagraph1?: string | null, introParagraph2?: string | null, valuesLabel?: string | null, valuesHeading?: string | null, values?: Array<{ __typename: 'AboutPageValues', id?: string | null, title: string, description?: string | null } | null> | null };

export type ServicesPagePartsFragment = { __typename: 'ServicesPage', heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, categories?: Array<{ __typename: 'ServicesPageCategories', category: string, description?: string | null, items?: Array<string | null> | null } | null> | null };

export type ContactPagePartsFragment = { __typename: 'ContactPage', heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, heroTitlePunctuation?: string | null, heroDescription?: string | null, trustIndicators?: Array<{ __typename: 'ContactPageTrustIndicators', icon?: string | null, title: string, description?: string | null } | null> | null };

export type ProjectQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProjectQuery = { __typename?: 'Query', project: { __typename: 'Project', id: string, title: string, slug: string, category: string, image?: string | null, year: string, order?: number | null, description: string, fullDescription?: string | null, gallery?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ProjectConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectFilter>;
}>;


export type ProjectConnectionQuery = { __typename?: 'Query', projectConnection: { __typename?: 'ProjectConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProjectConnectionEdges', cursor: string, node?: { __typename: 'Project', id: string, title: string, slug: string, category: string, image?: string | null, year: string, order?: number | null, description: string, fullDescription?: string | null, gallery?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type TeamMemberQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TeamMemberQuery = { __typename?: 'Query', teamMember: { __typename: 'TeamMember', id: string, name: string, role: string, image?: string | null, bio?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type TeamMemberConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TeamMemberFilter>;
}>;


export type TeamMemberConnectionQuery = { __typename?: 'Query', teamMemberConnection: { __typename?: 'TeamMemberConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TeamMemberConnectionEdges', cursor: string, node?: { __typename: 'TeamMember', id: string, name: string, role: string, image?: string | null, bio?: string | null, order?: number | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SiteSettingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteSettingsQuery = { __typename?: 'Query', siteSettings: { __typename: 'SiteSettings', id: string, email: string, phone: string, phoneLink?: string | null, address?: string | null, copyright?: string | null, contactHeadingLine1?: string | null, contactHeadingLine2?: string | null, scrollText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, socials?: Array<{ __typename: 'SiteSettingsSocials', name: string, url: string } | null> | null, footerLinks?: Array<{ __typename: 'SiteSettingsFooterLinks', label: string, url: string } | null> | null } };

export type SiteSettingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteSettingsFilter>;
}>;


export type SiteSettingsConnectionQuery = { __typename?: 'Query', siteSettingsConnection: { __typename?: 'SiteSettingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteSettingsConnectionEdges', cursor: string, node?: { __typename: 'SiteSettings', id: string, email: string, phone: string, phoneLink?: string | null, address?: string | null, copyright?: string | null, contactHeadingLine1?: string | null, contactHeadingLine2?: string | null, scrollText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, socials?: Array<{ __typename: 'SiteSettingsSocials', name: string, url: string } | null> | null, footerLinks?: Array<{ __typename: 'SiteSettingsFooterLinks', label: string, url: string } | null> | null } | null } | null> | null } };

export type PartnersQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PartnersQuery = { __typename?: 'Query', partners: { __typename: 'Partners', id: string, partnersLabel: string, partners?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PartnersConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PartnersFilter>;
}>;


export type PartnersConnectionQuery = { __typename?: 'Query', partnersConnection: { __typename?: 'PartnersConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PartnersConnectionEdges', cursor: string, node?: { __typename: 'Partners', id: string, partnersLabel: string, partners?: Array<string | null> | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type HomePageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomePageQuery = { __typename?: 'Query', homePage: { __typename: 'HomePage', id: string, heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, heroDescription?: string | null, aboutHeading?: string | null, aboutParagraph1?: string | null, aboutParagraph2?: string | null, servicesHeading?: string | null, servicesSubtext?: string | null, servicesButtonText?: string | null, processHeading?: string | null, processSubtext?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, services?: Array<{ __typename: 'HomePageServices', id?: string | null, title: string, description?: string | null } | null> | null, processSteps?: Array<{ __typename: 'HomePageProcessSteps', num?: string | null, title: string, description?: string | null, tags?: Array<string | null> | null } | null> | null } };

export type HomePageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomePageFilter>;
}>;


export type HomePageConnectionQuery = { __typename?: 'Query', homePageConnection: { __typename?: 'HomePageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomePageConnectionEdges', cursor: string, node?: { __typename: 'HomePage', id: string, heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, heroDescription?: string | null, aboutHeading?: string | null, aboutParagraph1?: string | null, aboutParagraph2?: string | null, servicesHeading?: string | null, servicesSubtext?: string | null, servicesButtonText?: string | null, processHeading?: string | null, processSubtext?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, services?: Array<{ __typename: 'HomePageServices', id?: string | null, title: string, description?: string | null } | null> | null, processSteps?: Array<{ __typename: 'HomePageProcessSteps', num?: string | null, title: string, description?: string | null, tags?: Array<string | null> | null } | null> | null } | null } | null> | null } };

export type AboutPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AboutPageQuery = { __typename?: 'Query', aboutPage: { __typename: 'AboutPage', id: string, heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, studioImage?: string | null, studioImageAlt?: string | null, introHeading?: string | null, introParagraph1?: string | null, introParagraph2?: string | null, valuesLabel?: string | null, valuesHeading?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, values?: Array<{ __typename: 'AboutPageValues', id?: string | null, title: string, description?: string | null } | null> | null } };

export type AboutPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutPageFilter>;
}>;


export type AboutPageConnectionQuery = { __typename?: 'Query', aboutPageConnection: { __typename?: 'AboutPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AboutPageConnectionEdges', cursor: string, node?: { __typename: 'AboutPage', id: string, heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, studioImage?: string | null, studioImageAlt?: string | null, introHeading?: string | null, introParagraph1?: string | null, introParagraph2?: string | null, valuesLabel?: string | null, valuesHeading?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, values?: Array<{ __typename: 'AboutPageValues', id?: string | null, title: string, description?: string | null } | null> | null } | null } | null> | null } };

export type ServicesPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ServicesPageQuery = { __typename?: 'Query', servicesPage: { __typename: 'ServicesPage', id: string, heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, categories?: Array<{ __typename: 'ServicesPageCategories', category: string, description?: string | null, items?: Array<string | null> | null } | null> | null } };

export type ServicesPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServicesPageFilter>;
}>;


export type ServicesPageConnectionQuery = { __typename?: 'Query', servicesPageConnection: { __typename?: 'ServicesPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ServicesPageConnectionEdges', cursor: string, node?: { __typename: 'ServicesPage', id: string, heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, categories?: Array<{ __typename: 'ServicesPageCategories', category: string, description?: string | null, items?: Array<string | null> | null } | null> | null } | null } | null> | null } };

export type ContactPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactPageQuery = { __typename?: 'Query', contactPage: { __typename: 'ContactPage', id: string, heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, heroTitlePunctuation?: string | null, heroDescription?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, trustIndicators?: Array<{ __typename: 'ContactPageTrustIndicators', icon?: string | null, title: string, description?: string | null } | null> | null } };

export type ContactPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactPageFilter>;
}>;


export type ContactPageConnectionQuery = { __typename?: 'Query', contactPageConnection: { __typename?: 'ContactPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactPageConnectionEdges', cursor: string, node?: { __typename: 'ContactPage', id: string, heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, heroTitlePunctuation?: string | null, heroDescription?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, trustIndicators?: Array<{ __typename: 'ContactPageTrustIndicators', icon?: string | null, title: string, description?: string | null } | null> | null } | null } | null> | null } };

export const ProjectPartsFragmentDoc = gql`
    fragment ProjectParts on Project {
  __typename
  title
  slug
  category
  image
  year
  order
  description
  fullDescription
  gallery
}
    `;
export const TeamMemberPartsFragmentDoc = gql`
    fragment TeamMemberParts on TeamMember {
  __typename
  name
  role
  image
  bio
  order
}
    `;
export const SiteSettingsPartsFragmentDoc = gql`
    fragment SiteSettingsParts on SiteSettings {
  __typename
  email
  phone
  phoneLink
  address
  copyright
  contactHeadingLine1
  contactHeadingLine2
  scrollText
  socials {
    __typename
    name
    url
  }
  footerLinks {
    __typename
    label
    url
  }
}
    `;
export const PartnersPartsFragmentDoc = gql`
    fragment PartnersParts on Partners {
  __typename
  partnersLabel
  partners
}
    `;
export const HomePagePartsFragmentDoc = gql`
    fragment HomePageParts on HomePage {
  __typename
  heroLabel
  heroTitleLine1
  heroTitleLine2
  heroDescription
  aboutHeading
  aboutParagraph1
  aboutParagraph2
  servicesHeading
  servicesSubtext
  servicesButtonText
  services {
    __typename
    id
    title
    description
  }
  processHeading
  processSubtext
  processSteps {
    __typename
    num
    title
    description
    tags
  }
}
    `;
export const AboutPagePartsFragmentDoc = gql`
    fragment AboutPageParts on AboutPage {
  __typename
  heroLabel
  heroTitleLine1
  heroTitleLine2
  studioImage
  studioImageAlt
  introHeading
  introParagraph1
  introParagraph2
  valuesLabel
  valuesHeading
  values {
    __typename
    id
    title
    description
  }
}
    `;
export const ServicesPagePartsFragmentDoc = gql`
    fragment ServicesPageParts on ServicesPage {
  __typename
  heroLabel
  heroTitleLine1
  heroTitleLine2
  categories {
    __typename
    category
    description
    items
  }
}
    `;
export const ContactPagePartsFragmentDoc = gql`
    fragment ContactPageParts on ContactPage {
  __typename
  heroLabel
  heroTitleLine1
  heroTitleLine2
  heroTitlePunctuation
  heroDescription
  trustIndicators {
    __typename
    icon
    title
    description
  }
}
    `;
export const ProjectDocument = gql`
    query project($relativePath: String!) {
  project(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProjectParts
  }
}
    ${ProjectPartsFragmentDoc}`;
export const ProjectConnectionDocument = gql`
    query projectConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProjectFilter) {
  projectConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProjectParts
      }
    }
  }
}
    ${ProjectPartsFragmentDoc}`;
export const TeamMemberDocument = gql`
    query teamMember($relativePath: String!) {
  teamMember(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TeamMemberParts
  }
}
    ${TeamMemberPartsFragmentDoc}`;
export const TeamMemberConnectionDocument = gql`
    query teamMemberConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TeamMemberFilter) {
  teamMemberConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TeamMemberParts
      }
    }
  }
}
    ${TeamMemberPartsFragmentDoc}`;
export const SiteSettingsDocument = gql`
    query siteSettings($relativePath: String!) {
  siteSettings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteSettingsParts
  }
}
    ${SiteSettingsPartsFragmentDoc}`;
export const SiteSettingsConnectionDocument = gql`
    query siteSettingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteSettingsFilter) {
  siteSettingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteSettingsParts
      }
    }
  }
}
    ${SiteSettingsPartsFragmentDoc}`;
export const PartnersDocument = gql`
    query partners($relativePath: String!) {
  partners(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PartnersParts
  }
}
    ${PartnersPartsFragmentDoc}`;
export const PartnersConnectionDocument = gql`
    query partnersConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PartnersFilter) {
  partnersConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PartnersParts
      }
    }
  }
}
    ${PartnersPartsFragmentDoc}`;
export const HomePageDocument = gql`
    query homePage($relativePath: String!) {
  homePage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomePageParts
  }
}
    ${HomePagePartsFragmentDoc}`;
export const HomePageConnectionDocument = gql`
    query homePageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomePageFilter) {
  homePageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomePageParts
      }
    }
  }
}
    ${HomePagePartsFragmentDoc}`;
export const AboutPageDocument = gql`
    query aboutPage($relativePath: String!) {
  aboutPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AboutPageParts
  }
}
    ${AboutPagePartsFragmentDoc}`;
export const AboutPageConnectionDocument = gql`
    query aboutPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AboutPageFilter) {
  aboutPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AboutPageParts
      }
    }
  }
}
    ${AboutPagePartsFragmentDoc}`;
export const ServicesPageDocument = gql`
    query servicesPage($relativePath: String!) {
  servicesPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServicesPageParts
  }
}
    ${ServicesPagePartsFragmentDoc}`;
export const ServicesPageConnectionDocument = gql`
    query servicesPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServicesPageFilter) {
  servicesPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServicesPageParts
      }
    }
  }
}
    ${ServicesPagePartsFragmentDoc}`;
export const ContactPageDocument = gql`
    query contactPage($relativePath: String!) {
  contactPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactPageParts
  }
}
    ${ContactPagePartsFragmentDoc}`;
export const ContactPageConnectionDocument = gql`
    query contactPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactPageFilter) {
  contactPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactPageParts
      }
    }
  }
}
    ${ContactPagePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      project(variables: ProjectQueryVariables, options?: C): Promise<{data: ProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectQueryVariables, query: string}> {
        return requester<{data: ProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectQueryVariables, query: string}, ProjectQueryVariables>(ProjectDocument, variables, options);
      },
    projectConnection(variables?: ProjectConnectionQueryVariables, options?: C): Promise<{data: ProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectConnectionQueryVariables, query: string}> {
        return requester<{data: ProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectConnectionQueryVariables, query: string}, ProjectConnectionQueryVariables>(ProjectConnectionDocument, variables, options);
      },
    teamMember(variables: TeamMemberQueryVariables, options?: C): Promise<{data: TeamMemberQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamMemberQueryVariables, query: string}> {
        return requester<{data: TeamMemberQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamMemberQueryVariables, query: string}, TeamMemberQueryVariables>(TeamMemberDocument, variables, options);
      },
    teamMemberConnection(variables?: TeamMemberConnectionQueryVariables, options?: C): Promise<{data: TeamMemberConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamMemberConnectionQueryVariables, query: string}> {
        return requester<{data: TeamMemberConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TeamMemberConnectionQueryVariables, query: string}, TeamMemberConnectionQueryVariables>(TeamMemberConnectionDocument, variables, options);
      },
    siteSettings(variables: SiteSettingsQueryVariables, options?: C): Promise<{data: SiteSettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsQueryVariables, query: string}> {
        return requester<{data: SiteSettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsQueryVariables, query: string}, SiteSettingsQueryVariables>(SiteSettingsDocument, variables, options);
      },
    siteSettingsConnection(variables?: SiteSettingsConnectionQueryVariables, options?: C): Promise<{data: SiteSettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SiteSettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsConnectionQueryVariables, query: string}, SiteSettingsConnectionQueryVariables>(SiteSettingsConnectionDocument, variables, options);
      },
    partners(variables: PartnersQueryVariables, options?: C): Promise<{data: PartnersQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartnersQueryVariables, query: string}> {
        return requester<{data: PartnersQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartnersQueryVariables, query: string}, PartnersQueryVariables>(PartnersDocument, variables, options);
      },
    partnersConnection(variables?: PartnersConnectionQueryVariables, options?: C): Promise<{data: PartnersConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartnersConnectionQueryVariables, query: string}> {
        return requester<{data: PartnersConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartnersConnectionQueryVariables, query: string}, PartnersConnectionQueryVariables>(PartnersConnectionDocument, variables, options);
      },
    homePage(variables: HomePageQueryVariables, options?: C): Promise<{data: HomePageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageQueryVariables, query: string}> {
        return requester<{data: HomePageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageQueryVariables, query: string}, HomePageQueryVariables>(HomePageDocument, variables, options);
      },
    homePageConnection(variables?: HomePageConnectionQueryVariables, options?: C): Promise<{data: HomePageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageConnectionQueryVariables, query: string}> {
        return requester<{data: HomePageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageConnectionQueryVariables, query: string}, HomePageConnectionQueryVariables>(HomePageConnectionDocument, variables, options);
      },
    aboutPage(variables: AboutPageQueryVariables, options?: C): Promise<{data: AboutPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutPageQueryVariables, query: string}> {
        return requester<{data: AboutPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutPageQueryVariables, query: string}, AboutPageQueryVariables>(AboutPageDocument, variables, options);
      },
    aboutPageConnection(variables?: AboutPageConnectionQueryVariables, options?: C): Promise<{data: AboutPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutPageConnectionQueryVariables, query: string}> {
        return requester<{data: AboutPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutPageConnectionQueryVariables, query: string}, AboutPageConnectionQueryVariables>(AboutPageConnectionDocument, variables, options);
      },
    servicesPage(variables: ServicesPageQueryVariables, options?: C): Promise<{data: ServicesPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesPageQueryVariables, query: string}> {
        return requester<{data: ServicesPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesPageQueryVariables, query: string}, ServicesPageQueryVariables>(ServicesPageDocument, variables, options);
      },
    servicesPageConnection(variables?: ServicesPageConnectionQueryVariables, options?: C): Promise<{data: ServicesPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesPageConnectionQueryVariables, query: string}> {
        return requester<{data: ServicesPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesPageConnectionQueryVariables, query: string}, ServicesPageConnectionQueryVariables>(ServicesPageConnectionDocument, variables, options);
      },
    contactPage(variables: ContactPageQueryVariables, options?: C): Promise<{data: ContactPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactPageQueryVariables, query: string}> {
        return requester<{data: ContactPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactPageQueryVariables, query: string}, ContactPageQueryVariables>(ContactPageDocument, variables, options);
      },
    contactPageConnection(variables?: ContactPageConnectionQueryVariables, options?: C): Promise<{data: ContactPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactPageConnectionQueryVariables, query: string}> {
        return requester<{data: ContactPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactPageConnectionQueryVariables, query: string}, ContactPageConnectionQueryVariables>(ContactPageConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "https://content.tinajs.io/2.1/content/43df9a3d-b238-44c9-8f2a-0b1563230ff6/github/main",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  