//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  project: Project;
  projectConnection: ProjectConnection;
  siteSettings: SiteSettings;
  siteSettingsConnection: SiteSettingsConnection;
  partners: Partners;
  partnersConnection: PartnersConnection;
  homePage: HomePage;
  homePageConnection: HomePageConnection;
  testimonialsPage: TestimonialsPage;
  testimonialsPageConnection: TestimonialsPageConnection;
  aboutPage: AboutPage;
  aboutPageConnection: AboutPageConnection;
  servicesPage: ServicesPage;
  servicesPageConnection: ServicesPageConnection;
  contactPage: ContactPage;
  contactPageConnection: ContactPageConnection;
  pricingPage: PricingPage;
  pricingPageConnection: PricingPageConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjectArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryProjectConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectFilter>;
};


export type QuerySiteSettingsArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QuerySiteSettingsConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteSettingsFilter>;
};


export type QueryPartnersArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPartnersConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PartnersFilter>;
};


export type QueryHomePageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryHomePageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomePageFilter>;
};


export type QueryTestimonialsPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryTestimonialsPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialsPageFilter>;
};


export type QueryAboutPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryAboutPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutPageFilter>;
};


export type QueryServicesPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryServicesPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServicesPageFilter>;
};


export type QueryContactPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryContactPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactPageFilter>;
};


export type QueryPricingPageArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPricingPageConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PricingPageFilter>;
};

export type DocumentFilter = {
  project?: InputMaybe<ProjectFilter>;
  siteSettings?: InputMaybe<SiteSettingsFilter>;
  partners?: InputMaybe<PartnersFilter>;
  homePage?: InputMaybe<HomePageFilter>;
  testimonialsPage?: InputMaybe<TestimonialsPageFilter>;
  aboutPage?: InputMaybe<AboutPageFilter>;
  servicesPage?: InputMaybe<ServicesPageFilter>;
  contactPage?: InputMaybe<ContactPageFilter>;
  pricingPage?: InputMaybe<PricingPageFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Project | SiteSettings | Partners | HomePage | TestimonialsPage | AboutPage | ServicesPage | ContactPage | PricingPage | Folder;

export type Project = Node & Document & {
  __typename?: 'Project';
  title: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  category: Array<Scalars['String']['output']>;
  techStack?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  image?: Maybe<Scalars['String']['output']>;
  year: Scalars['String']['output'];
  order?: Maybe<Scalars['Float']['output']>;
  featuredOnHome?: Maybe<Scalars['Boolean']['output']>;
  description: Scalars['String']['output'];
  fullDescription?: Maybe<Scalars['String']['output']>;
  gallery?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  siteUrl?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type BooleanFilter = {
  eq?: InputMaybe<Scalars['Boolean']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
};

export type ProjectFilter = {
  title?: InputMaybe<StringFilter>;
  slug?: InputMaybe<StringFilter>;
  category?: InputMaybe<StringFilter>;
  techStack?: InputMaybe<StringFilter>;
  image?: InputMaybe<StringFilter>;
  year?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
  featuredOnHome?: InputMaybe<BooleanFilter>;
  description?: InputMaybe<StringFilter>;
  fullDescription?: InputMaybe<StringFilter>;
  gallery?: InputMaybe<StringFilter>;
  siteUrl?: InputMaybe<StringFilter>;
};

export type ProjectConnectionEdges = {
  __typename?: 'ProjectConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Project>;
};

export type ProjectConnection = Connection & {
  __typename?: 'ProjectConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ProjectConnectionEdges>>>;
};

export type SiteSettingsSocials = {
  __typename?: 'SiteSettingsSocials';
  name: Scalars['String']['output'];
  url: Scalars['String']['output'];
  openInNewTab?: Maybe<Scalars['Boolean']['output']>;
};

export type SiteSettingsFooterLinks = {
  __typename?: 'SiteSettingsFooterLinks';
  label: Scalars['String']['output'];
  url: Scalars['String']['output'];
};

export type SiteSettings = Node & Document & {
  __typename?: 'SiteSettings';
  email: Scalars['String']['output'];
  phone: Scalars['String']['output'];
  phoneLink?: Maybe<Scalars['String']['output']>;
  address?: Maybe<Scalars['String']['output']>;
  copyright?: Maybe<Scalars['String']['output']>;
  contactHeadingLine1?: Maybe<Scalars['String']['output']>;
  contactHeadingLine2?: Maybe<Scalars['String']['output']>;
  scrollText?: Maybe<Scalars['String']['output']>;
  socials?: Maybe<Array<Maybe<SiteSettingsSocials>>>;
  footerLinks?: Maybe<Array<Maybe<SiteSettingsFooterLinks>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type SiteSettingsSocialsFilter = {
  name?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
  openInNewTab?: InputMaybe<BooleanFilter>;
};

export type SiteSettingsFooterLinksFilter = {
  label?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type SiteSettingsFilter = {
  email?: InputMaybe<StringFilter>;
  phone?: InputMaybe<StringFilter>;
  phoneLink?: InputMaybe<StringFilter>;
  address?: InputMaybe<StringFilter>;
  copyright?: InputMaybe<StringFilter>;
  contactHeadingLine1?: InputMaybe<StringFilter>;
  contactHeadingLine2?: InputMaybe<StringFilter>;
  scrollText?: InputMaybe<StringFilter>;
  socials?: InputMaybe<SiteSettingsSocialsFilter>;
  footerLinks?: InputMaybe<SiteSettingsFooterLinksFilter>;
};

export type SiteSettingsConnectionEdges = {
  __typename?: 'SiteSettingsConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<SiteSettings>;
};

export type SiteSettingsConnection = Connection & {
  __typename?: 'SiteSettingsConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<SiteSettingsConnectionEdges>>>;
};

export type PartnersPartners = {
  __typename?: 'PartnersPartners';
  name: Scalars['String']['output'];
  url?: Maybe<Scalars['String']['output']>;
};

export type Partners = Node & Document & {
  __typename?: 'Partners';
  partnersLabel: Scalars['String']['output'];
  partners?: Maybe<Array<Maybe<PartnersPartners>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PartnersPartnersFilter = {
  name?: InputMaybe<StringFilter>;
  url?: InputMaybe<StringFilter>;
};

export type PartnersFilter = {
  partnersLabel?: InputMaybe<StringFilter>;
  partners?: InputMaybe<PartnersPartnersFilter>;
};

export type PartnersConnectionEdges = {
  __typename?: 'PartnersConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Partners>;
};

export type PartnersConnection = Connection & {
  __typename?: 'PartnersConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PartnersConnectionEdges>>>;
};

export type HomePageServices = {
  __typename?: 'HomePageServices';
  id?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
};

export type HomePageProcessSteps = {
  __typename?: 'HomePageProcessSteps';
  num?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  tags?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type HomePage = Node & Document & {
  __typename?: 'HomePage';
  heroLabel: Scalars['String']['output'];
  heroTitleLine1?: Maybe<Scalars['String']['output']>;
  heroTitleLine2?: Maybe<Scalars['String']['output']>;
  heroDescription?: Maybe<Scalars['String']['output']>;
  aboutHeading?: Maybe<Scalars['String']['output']>;
  aboutParagraph1?: Maybe<Scalars['String']['output']>;
  aboutParagraph2?: Maybe<Scalars['String']['output']>;
  servicesHeading?: Maybe<Scalars['String']['output']>;
  servicesSubtext?: Maybe<Scalars['String']['output']>;
  servicesButtonText?: Maybe<Scalars['String']['output']>;
  services?: Maybe<Array<Maybe<HomePageServices>>>;
  processHeading?: Maybe<Scalars['String']['output']>;
  processSubtext?: Maybe<Scalars['String']['output']>;
  processSteps?: Maybe<Array<Maybe<HomePageProcessSteps>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type HomePageServicesFilter = {
  id?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type HomePageProcessStepsFilter = {
  num?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  tags?: InputMaybe<StringFilter>;
};

export type HomePageFilter = {
  heroLabel?: InputMaybe<StringFilter>;
  heroTitleLine1?: InputMaybe<StringFilter>;
  heroTitleLine2?: InputMaybe<StringFilter>;
  heroDescription?: InputMaybe<StringFilter>;
  aboutHeading?: InputMaybe<StringFilter>;
  aboutParagraph1?: InputMaybe<StringFilter>;
  aboutParagraph2?: InputMaybe<StringFilter>;
  servicesHeading?: InputMaybe<StringFilter>;
  servicesSubtext?: InputMaybe<StringFilter>;
  servicesButtonText?: InputMaybe<StringFilter>;
  services?: InputMaybe<HomePageServicesFilter>;
  processHeading?: InputMaybe<StringFilter>;
  processSubtext?: InputMaybe<StringFilter>;
  processSteps?: InputMaybe<HomePageProcessStepsFilter>;
};

export type HomePageConnectionEdges = {
  __typename?: 'HomePageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<HomePage>;
};

export type HomePageConnection = Connection & {
  __typename?: 'HomePageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<HomePageConnectionEdges>>>;
};

export type TestimonialsPageTestimonials = {
  __typename?: 'TestimonialsPageTestimonials';
  quote: Scalars['String']['output'];
  name: Scalars['String']['output'];
  role: Scalars['String']['output'];
  company?: Maybe<Scalars['String']['output']>;
};

export type TestimonialsPage = Node & Document & {
  __typename?: 'TestimonialsPage';
  heading: Scalars['String']['output'];
  subtext?: Maybe<Scalars['String']['output']>;
  testimonials?: Maybe<Array<Maybe<TestimonialsPageTestimonials>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type TestimonialsPageTestimonialsFilter = {
  quote?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  company?: InputMaybe<StringFilter>;
};

export type TestimonialsPageFilter = {
  heading?: InputMaybe<StringFilter>;
  subtext?: InputMaybe<StringFilter>;
  testimonials?: InputMaybe<TestimonialsPageTestimonialsFilter>;
};

export type TestimonialsPageConnectionEdges = {
  __typename?: 'TestimonialsPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<TestimonialsPage>;
};

export type TestimonialsPageConnection = Connection & {
  __typename?: 'TestimonialsPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<TestimonialsPageConnectionEdges>>>;
};

export type AboutPageValues = {
  __typename?: 'AboutPageValues';
  id?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
};

export type AboutPageTeamMembers = {
  __typename?: 'AboutPageTeamMembers';
  name: Scalars['String']['output'];
  role: Scalars['String']['output'];
  image?: Maybe<Scalars['String']['output']>;
  bio?: Maybe<Scalars['String']['output']>;
  order?: Maybe<Scalars['Float']['output']>;
};

export type AboutPage = Node & Document & {
  __typename?: 'AboutPage';
  heroLabel: Scalars['String']['output'];
  heroTitleLine1?: Maybe<Scalars['String']['output']>;
  heroTitleLine2?: Maybe<Scalars['String']['output']>;
  studioImage?: Maybe<Scalars['String']['output']>;
  studioImageAlt?: Maybe<Scalars['String']['output']>;
  introHeading?: Maybe<Scalars['String']['output']>;
  introParagraph1?: Maybe<Scalars['String']['output']>;
  introParagraph2?: Maybe<Scalars['String']['output']>;
  valuesLabel?: Maybe<Scalars['String']['output']>;
  valuesHeading?: Maybe<Scalars['String']['output']>;
  values?: Maybe<Array<Maybe<AboutPageValues>>>;
  teamMembers?: Maybe<Array<Maybe<AboutPageTeamMembers>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type AboutPageValuesFilter = {
  id?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type AboutPageTeamMembersFilter = {
  name?: InputMaybe<StringFilter>;
  role?: InputMaybe<StringFilter>;
  image?: InputMaybe<StringFilter>;
  bio?: InputMaybe<StringFilter>;
  order?: InputMaybe<NumberFilter>;
};

export type AboutPageFilter = {
  heroLabel?: InputMaybe<StringFilter>;
  heroTitleLine1?: InputMaybe<StringFilter>;
  heroTitleLine2?: InputMaybe<StringFilter>;
  studioImage?: InputMaybe<StringFilter>;
  studioImageAlt?: InputMaybe<StringFilter>;
  introHeading?: InputMaybe<StringFilter>;
  introParagraph1?: InputMaybe<StringFilter>;
  introParagraph2?: InputMaybe<StringFilter>;
  valuesLabel?: InputMaybe<StringFilter>;
  valuesHeading?: InputMaybe<StringFilter>;
  values?: InputMaybe<AboutPageValuesFilter>;
  teamMembers?: InputMaybe<AboutPageTeamMembersFilter>;
};

export type AboutPageConnectionEdges = {
  __typename?: 'AboutPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<AboutPage>;
};

export type AboutPageConnection = Connection & {
  __typename?: 'AboutPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<AboutPageConnectionEdges>>>;
};

export type ServicesPageCategories = {
  __typename?: 'ServicesPageCategories';
  category: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
  items?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
};

export type ServicesPage = Node & Document & {
  __typename?: 'ServicesPage';
  heroLabel: Scalars['String']['output'];
  heroTitleLine1?: Maybe<Scalars['String']['output']>;
  heroTitleLine2?: Maybe<Scalars['String']['output']>;
  categories?: Maybe<Array<Maybe<ServicesPageCategories>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ServicesPageCategoriesFilter = {
  category?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
  items?: InputMaybe<StringFilter>;
};

export type ServicesPageFilter = {
  heroLabel?: InputMaybe<StringFilter>;
  heroTitleLine1?: InputMaybe<StringFilter>;
  heroTitleLine2?: InputMaybe<StringFilter>;
  categories?: InputMaybe<ServicesPageCategoriesFilter>;
};

export type ServicesPageConnectionEdges = {
  __typename?: 'ServicesPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ServicesPage>;
};

export type ServicesPageConnection = Connection & {
  __typename?: 'ServicesPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ServicesPageConnectionEdges>>>;
};

export type ContactPageTrustIndicators = {
  __typename?: 'ContactPageTrustIndicators';
  icon?: Maybe<Scalars['String']['output']>;
  title: Scalars['String']['output'];
  description?: Maybe<Scalars['String']['output']>;
};

export type ContactPage = Node & Document & {
  __typename?: 'ContactPage';
  heroLabel: Scalars['String']['output'];
  heroTitleLine1?: Maybe<Scalars['String']['output']>;
  heroTitleLine2?: Maybe<Scalars['String']['output']>;
  heroTitlePunctuation?: Maybe<Scalars['String']['output']>;
  heroDescription?: Maybe<Scalars['String']['output']>;
  trustIndicators?: Maybe<Array<Maybe<ContactPageTrustIndicators>>>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type ContactPageTrustIndicatorsFilter = {
  icon?: InputMaybe<StringFilter>;
  title?: InputMaybe<StringFilter>;
  description?: InputMaybe<StringFilter>;
};

export type ContactPageFilter = {
  heroLabel?: InputMaybe<StringFilter>;
  heroTitleLine1?: InputMaybe<StringFilter>;
  heroTitleLine2?: InputMaybe<StringFilter>;
  heroTitlePunctuation?: InputMaybe<StringFilter>;
  heroDescription?: InputMaybe<StringFilter>;
  trustIndicators?: InputMaybe<ContactPageTrustIndicatorsFilter>;
};

export type ContactPageConnectionEdges = {
  __typename?: 'ContactPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<ContactPage>;
};

export type ContactPageConnection = Connection & {
  __typename?: 'ContactPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<ContactPageConnectionEdges>>>;
};

export type PricingPagePlansCtaLink = {
  __typename?: 'PricingPagePlansCtaLink';
  linkType?: Maybe<Scalars['String']['output']>;
  linkValue?: Maybe<Scalars['String']['output']>;
};

export type PricingPagePlans = {
  __typename?: 'PricingPagePlans';
  label?: Maybe<Scalars['String']['output']>;
  name: Scalars['String']['output'];
  price: Scalars['String']['output'];
  priceNote?: Maybe<Scalars['String']['output']>;
  delivery?: Maybe<Scalars['String']['output']>;
  tagline?: Maybe<Scalars['String']['output']>;
  featured?: Maybe<Scalars['Boolean']['output']>;
  ctaLabel?: Maybe<Scalars['String']['output']>;
  ctaLink?: Maybe<PricingPagePlansCtaLink>;
  features?: Maybe<Array<Maybe<Scalars['String']['output']>>>;
  bestFor?: Maybe<Scalars['String']['output']>;
  revisions?: Maybe<Scalars['String']['output']>;
};

export type PricingPage = Node & Document & {
  __typename?: 'PricingPage';
  heroLabel: Scalars['String']['output'];
  heroTitleLine1?: Maybe<Scalars['String']['output']>;
  heroTitleLine2?: Maybe<Scalars['String']['output']>;
  heroSubtext?: Maybe<Scalars['String']['output']>;
  sectionLabel?: Maybe<Scalars['String']['output']>;
  sectionHeading?: Maybe<Scalars['String']['output']>;
  sectionSubtext?: Maybe<Scalars['String']['output']>;
  plans?: Maybe<Array<Maybe<PricingPagePlans>>>;
  customLabel?: Maybe<Scalars['String']['output']>;
  customDescription?: Maybe<Scalars['String']['output']>;
  customCtaLabel?: Maybe<Scalars['String']['output']>;
  customCtaHref?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type PricingPagePlansCtaLinkFilter = {
  linkType?: InputMaybe<StringFilter>;
  linkValue?: InputMaybe<StringFilter>;
};

export type PricingPagePlansFilter = {
  label?: InputMaybe<StringFilter>;
  name?: InputMaybe<StringFilter>;
  price?: InputMaybe<StringFilter>;
  priceNote?: InputMaybe<StringFilter>;
  delivery?: InputMaybe<StringFilter>;
  tagline?: InputMaybe<StringFilter>;
  featured?: InputMaybe<BooleanFilter>;
  ctaLabel?: InputMaybe<StringFilter>;
  ctaLink?: InputMaybe<PricingPagePlansCtaLinkFilter>;
  features?: InputMaybe<StringFilter>;
  bestFor?: InputMaybe<StringFilter>;
  revisions?: InputMaybe<StringFilter>;
};

export type PricingPageFilter = {
  heroLabel?: InputMaybe<StringFilter>;
  heroTitleLine1?: InputMaybe<StringFilter>;
  heroTitleLine2?: InputMaybe<StringFilter>;
  heroSubtext?: InputMaybe<StringFilter>;
  sectionLabel?: InputMaybe<StringFilter>;
  sectionHeading?: InputMaybe<StringFilter>;
  sectionSubtext?: InputMaybe<StringFilter>;
  plans?: InputMaybe<PricingPagePlansFilter>;
  customLabel?: InputMaybe<StringFilter>;
  customDescription?: InputMaybe<StringFilter>;
  customCtaLabel?: InputMaybe<StringFilter>;
  customCtaHref?: InputMaybe<StringFilter>;
};

export type PricingPageConnectionEdges = {
  __typename?: 'PricingPageConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<PricingPage>;
};

export type PricingPageConnection = Connection & {
  __typename?: 'PricingPageConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PricingPageConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updateProject: Project;
  createProject: Project;
  updateSiteSettings: SiteSettings;
  createSiteSettings: SiteSettings;
  updatePartners: Partners;
  createPartners: Partners;
  updateHomePage: HomePage;
  createHomePage: HomePage;
  updateTestimonialsPage: TestimonialsPage;
  createTestimonialsPage: TestimonialsPage;
  updateAboutPage: AboutPage;
  createAboutPage: AboutPage;
  updateServicesPage: ServicesPage;
  createServicesPage: ServicesPage;
  updateContactPage: ContactPage;
  createContactPage: ContactPage;
  updatePricingPage: PricingPage;
  createPricingPage: PricingPage;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdateProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectMutation;
};


export type MutationCreateProjectArgs = {
  relativePath: Scalars['String']['input'];
  params: ProjectMutation;
};


export type MutationUpdateSiteSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteSettingsMutation;
};


export type MutationCreateSiteSettingsArgs = {
  relativePath: Scalars['String']['input'];
  params: SiteSettingsMutation;
};


export type MutationUpdatePartnersArgs = {
  relativePath: Scalars['String']['input'];
  params: PartnersMutation;
};


export type MutationCreatePartnersArgs = {
  relativePath: Scalars['String']['input'];
  params: PartnersMutation;
};


export type MutationUpdateHomePageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomePageMutation;
};


export type MutationCreateHomePageArgs = {
  relativePath: Scalars['String']['input'];
  params: HomePageMutation;
};


export type MutationUpdateTestimonialsPageArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialsPageMutation;
};


export type MutationCreateTestimonialsPageArgs = {
  relativePath: Scalars['String']['input'];
  params: TestimonialsPageMutation;
};


export type MutationUpdateAboutPageArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutPageMutation;
};


export type MutationCreateAboutPageArgs = {
  relativePath: Scalars['String']['input'];
  params: AboutPageMutation;
};


export type MutationUpdateServicesPageArgs = {
  relativePath: Scalars['String']['input'];
  params: ServicesPageMutation;
};


export type MutationCreateServicesPageArgs = {
  relativePath: Scalars['String']['input'];
  params: ServicesPageMutation;
};


export type MutationUpdateContactPageArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactPageMutation;
};


export type MutationCreateContactPageArgs = {
  relativePath: Scalars['String']['input'];
  params: ContactPageMutation;
};


export type MutationUpdatePricingPageArgs = {
  relativePath: Scalars['String']['input'];
  params: PricingPageMutation;
};


export type MutationCreatePricingPageArgs = {
  relativePath: Scalars['String']['input'];
  params: PricingPageMutation;
};

export type DocumentUpdateMutation = {
  project?: InputMaybe<ProjectMutation>;
  siteSettings?: InputMaybe<SiteSettingsMutation>;
  partners?: InputMaybe<PartnersMutation>;
  homePage?: InputMaybe<HomePageMutation>;
  testimonialsPage?: InputMaybe<TestimonialsPageMutation>;
  aboutPage?: InputMaybe<AboutPageMutation>;
  servicesPage?: InputMaybe<ServicesPageMutation>;
  contactPage?: InputMaybe<ContactPageMutation>;
  pricingPage?: InputMaybe<PricingPageMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  project?: InputMaybe<ProjectMutation>;
  siteSettings?: InputMaybe<SiteSettingsMutation>;
  partners?: InputMaybe<PartnersMutation>;
  homePage?: InputMaybe<HomePageMutation>;
  testimonialsPage?: InputMaybe<TestimonialsPageMutation>;
  aboutPage?: InputMaybe<AboutPageMutation>;
  servicesPage?: InputMaybe<ServicesPageMutation>;
  contactPage?: InputMaybe<ContactPageMutation>;
  pricingPage?: InputMaybe<PricingPageMutation>;
};

export type ProjectMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  slug?: InputMaybe<Scalars['String']['input']>;
  category?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  techStack?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  image?: InputMaybe<Scalars['String']['input']>;
  year?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
  featuredOnHome?: InputMaybe<Scalars['Boolean']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  fullDescription?: InputMaybe<Scalars['String']['input']>;
  gallery?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  siteUrl?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSettingsSocialsMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
  openInNewTab?: InputMaybe<Scalars['Boolean']['input']>;
};

export type SiteSettingsFooterLinksMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type SiteSettingsMutation = {
  email?: InputMaybe<Scalars['String']['input']>;
  phone?: InputMaybe<Scalars['String']['input']>;
  phoneLink?: InputMaybe<Scalars['String']['input']>;
  address?: InputMaybe<Scalars['String']['input']>;
  copyright?: InputMaybe<Scalars['String']['input']>;
  contactHeadingLine1?: InputMaybe<Scalars['String']['input']>;
  contactHeadingLine2?: InputMaybe<Scalars['String']['input']>;
  scrollText?: InputMaybe<Scalars['String']['input']>;
  socials?: InputMaybe<Array<InputMaybe<SiteSettingsSocialsMutation>>>;
  footerLinks?: InputMaybe<Array<InputMaybe<SiteSettingsFooterLinksMutation>>>;
};

export type PartnersPartnersMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  url?: InputMaybe<Scalars['String']['input']>;
};

export type PartnersMutation = {
  partnersLabel?: InputMaybe<Scalars['String']['input']>;
  partners?: InputMaybe<Array<InputMaybe<PartnersPartnersMutation>>>;
};

export type HomePageServicesMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type HomePageProcessStepsMutation = {
  num?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  tags?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type HomePageMutation = {
  heroLabel?: InputMaybe<Scalars['String']['input']>;
  heroTitleLine1?: InputMaybe<Scalars['String']['input']>;
  heroTitleLine2?: InputMaybe<Scalars['String']['input']>;
  heroDescription?: InputMaybe<Scalars['String']['input']>;
  aboutHeading?: InputMaybe<Scalars['String']['input']>;
  aboutParagraph1?: InputMaybe<Scalars['String']['input']>;
  aboutParagraph2?: InputMaybe<Scalars['String']['input']>;
  servicesHeading?: InputMaybe<Scalars['String']['input']>;
  servicesSubtext?: InputMaybe<Scalars['String']['input']>;
  servicesButtonText?: InputMaybe<Scalars['String']['input']>;
  services?: InputMaybe<Array<InputMaybe<HomePageServicesMutation>>>;
  processHeading?: InputMaybe<Scalars['String']['input']>;
  processSubtext?: InputMaybe<Scalars['String']['input']>;
  processSteps?: InputMaybe<Array<InputMaybe<HomePageProcessStepsMutation>>>;
};

export type TestimonialsPageTestimonialsMutation = {
  quote?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  company?: InputMaybe<Scalars['String']['input']>;
};

export type TestimonialsPageMutation = {
  heading?: InputMaybe<Scalars['String']['input']>;
  subtext?: InputMaybe<Scalars['String']['input']>;
  testimonials?: InputMaybe<Array<InputMaybe<TestimonialsPageTestimonialsMutation>>>;
};

export type AboutPageValuesMutation = {
  id?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type AboutPageTeamMembersMutation = {
  name?: InputMaybe<Scalars['String']['input']>;
  role?: InputMaybe<Scalars['String']['input']>;
  image?: InputMaybe<Scalars['String']['input']>;
  bio?: InputMaybe<Scalars['String']['input']>;
  order?: InputMaybe<Scalars['Float']['input']>;
};

export type AboutPageMutation = {
  heroLabel?: InputMaybe<Scalars['String']['input']>;
  heroTitleLine1?: InputMaybe<Scalars['String']['input']>;
  heroTitleLine2?: InputMaybe<Scalars['String']['input']>;
  studioImage?: InputMaybe<Scalars['String']['input']>;
  studioImageAlt?: InputMaybe<Scalars['String']['input']>;
  introHeading?: InputMaybe<Scalars['String']['input']>;
  introParagraph1?: InputMaybe<Scalars['String']['input']>;
  introParagraph2?: InputMaybe<Scalars['String']['input']>;
  valuesLabel?: InputMaybe<Scalars['String']['input']>;
  valuesHeading?: InputMaybe<Scalars['String']['input']>;
  values?: InputMaybe<Array<InputMaybe<AboutPageValuesMutation>>>;
  teamMembers?: InputMaybe<Array<InputMaybe<AboutPageTeamMembersMutation>>>;
};

export type ServicesPageCategoriesMutation = {
  category?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  items?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ServicesPageMutation = {
  heroLabel?: InputMaybe<Scalars['String']['input']>;
  heroTitleLine1?: InputMaybe<Scalars['String']['input']>;
  heroTitleLine2?: InputMaybe<Scalars['String']['input']>;
  categories?: InputMaybe<Array<InputMaybe<ServicesPageCategoriesMutation>>>;
};

export type ContactPageTrustIndicatorsMutation = {
  icon?: InputMaybe<Scalars['String']['input']>;
  title?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
};

export type ContactPageMutation = {
  heroLabel?: InputMaybe<Scalars['String']['input']>;
  heroTitleLine1?: InputMaybe<Scalars['String']['input']>;
  heroTitleLine2?: InputMaybe<Scalars['String']['input']>;
  heroTitlePunctuation?: InputMaybe<Scalars['String']['input']>;
  heroDescription?: InputMaybe<Scalars['String']['input']>;
  trustIndicators?: InputMaybe<Array<InputMaybe<ContactPageTrustIndicatorsMutation>>>;
};

export type PricingPagePlansCtaLinkMutation = {
  linkType?: InputMaybe<Scalars['String']['input']>;
  linkValue?: InputMaybe<Scalars['String']['input']>;
};

export type PricingPagePlansMutation = {
  label?: InputMaybe<Scalars['String']['input']>;
  name?: InputMaybe<Scalars['String']['input']>;
  price?: InputMaybe<Scalars['String']['input']>;
  priceNote?: InputMaybe<Scalars['String']['input']>;
  delivery?: InputMaybe<Scalars['String']['input']>;
  tagline?: InputMaybe<Scalars['String']['input']>;
  featured?: InputMaybe<Scalars['Boolean']['input']>;
  ctaLabel?: InputMaybe<Scalars['String']['input']>;
  ctaLink?: InputMaybe<PricingPagePlansCtaLinkMutation>;
  features?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
  bestFor?: InputMaybe<Scalars['String']['input']>;
  revisions?: InputMaybe<Scalars['String']['input']>;
};

export type PricingPageMutation = {
  heroLabel?: InputMaybe<Scalars['String']['input']>;
  heroTitleLine1?: InputMaybe<Scalars['String']['input']>;
  heroTitleLine2?: InputMaybe<Scalars['String']['input']>;
  heroSubtext?: InputMaybe<Scalars['String']['input']>;
  sectionLabel?: InputMaybe<Scalars['String']['input']>;
  sectionHeading?: InputMaybe<Scalars['String']['input']>;
  sectionSubtext?: InputMaybe<Scalars['String']['input']>;
  plans?: InputMaybe<Array<InputMaybe<PricingPagePlansMutation>>>;
  customLabel?: InputMaybe<Scalars['String']['input']>;
  customDescription?: InputMaybe<Scalars['String']['input']>;
  customCtaLabel?: InputMaybe<Scalars['String']['input']>;
  customCtaHref?: InputMaybe<Scalars['String']['input']>;
};

export type ProjectPartsFragment = { __typename: 'Project', title: string, slug: string, category: Array<string>, techStack?: Array<string | null> | null, image?: string | null, year: string, order?: number | null, featuredOnHome?: boolean | null, description: string, fullDescription?: string | null, gallery?: Array<string | null> | null, siteUrl?: string | null };

export type SiteSettingsPartsFragment = { __typename: 'SiteSettings', email: string, phone: string, phoneLink?: string | null, address?: string | null, copyright?: string | null, contactHeadingLine1?: string | null, contactHeadingLine2?: string | null, scrollText?: string | null, socials?: Array<{ __typename: 'SiteSettingsSocials', name: string, url: string, openInNewTab?: boolean | null } | null> | null, footerLinks?: Array<{ __typename: 'SiteSettingsFooterLinks', label: string, url: string } | null> | null };

export type PartnersPartsFragment = { __typename: 'Partners', partnersLabel: string, partners?: Array<{ __typename: 'PartnersPartners', name: string, url?: string | null } | null> | null };

export type HomePagePartsFragment = { __typename: 'HomePage', heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, heroDescription?: string | null, aboutHeading?: string | null, aboutParagraph1?: string | null, aboutParagraph2?: string | null, servicesHeading?: string | null, servicesSubtext?: string | null, servicesButtonText?: string | null, processHeading?: string | null, processSubtext?: string | null, services?: Array<{ __typename: 'HomePageServices', id?: string | null, title: string, description?: string | null } | null> | null, processSteps?: Array<{ __typename: 'HomePageProcessSteps', num?: string | null, title: string, description?: string | null, tags?: Array<string | null> | null } | null> | null };

export type TestimonialsPagePartsFragment = { __typename: 'TestimonialsPage', heading: string, subtext?: string | null, testimonials?: Array<{ __typename: 'TestimonialsPageTestimonials', quote: string, name: string, role: string, company?: string | null } | null> | null };

export type AboutPagePartsFragment = { __typename: 'AboutPage', heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, studioImage?: string | null, studioImageAlt?: string | null, introHeading?: string | null, introParagraph1?: string | null, introParagraph2?: string | null, valuesLabel?: string | null, valuesHeading?: string | null, values?: Array<{ __typename: 'AboutPageValues', id?: string | null, title: string, description?: string | null } | null> | null, teamMembers?: Array<{ __typename: 'AboutPageTeamMembers', name: string, role: string, image?: string | null, bio?: string | null, order?: number | null } | null> | null };

export type ServicesPagePartsFragment = { __typename: 'ServicesPage', heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, categories?: Array<{ __typename: 'ServicesPageCategories', category: string, description?: string | null, items?: Array<string | null> | null } | null> | null };

export type ContactPagePartsFragment = { __typename: 'ContactPage', heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, heroTitlePunctuation?: string | null, heroDescription?: string | null, trustIndicators?: Array<{ __typename: 'ContactPageTrustIndicators', icon?: string | null, title: string, description?: string | null } | null> | null };

export type PricingPagePartsFragment = { __typename: 'PricingPage', heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, heroSubtext?: string | null, sectionLabel?: string | null, sectionHeading?: string | null, sectionSubtext?: string | null, customLabel?: string | null, customDescription?: string | null, customCtaLabel?: string | null, customCtaHref?: string | null, plans?: Array<{ __typename: 'PricingPagePlans', label?: string | null, name: string, price: string, priceNote?: string | null, delivery?: string | null, tagline?: string | null, featured?: boolean | null, ctaLabel?: string | null, features?: Array<string | null> | null, bestFor?: string | null, revisions?: string | null, ctaLink?: { __typename: 'PricingPagePlansCtaLink', linkType?: string | null, linkValue?: string | null } | null } | null> | null };

export type ProjectQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ProjectQuery = { __typename?: 'Query', project: { __typename: 'Project', id: string, title: string, slug: string, category: Array<string>, techStack?: Array<string | null> | null, image?: string | null, year: string, order?: number | null, featuredOnHome?: boolean | null, description: string, fullDescription?: string | null, gallery?: Array<string | null> | null, siteUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type ProjectConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ProjectFilter>;
}>;


export type ProjectConnectionQuery = { __typename?: 'Query', projectConnection: { __typename?: 'ProjectConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ProjectConnectionEdges', cursor: string, node?: { __typename: 'Project', id: string, title: string, slug: string, category: Array<string>, techStack?: Array<string | null> | null, image?: string | null, year: string, order?: number | null, featuredOnHome?: boolean | null, description: string, fullDescription?: string | null, gallery?: Array<string | null> | null, siteUrl?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type SiteSettingsQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type SiteSettingsQuery = { __typename?: 'Query', siteSettings: { __typename: 'SiteSettings', id: string, email: string, phone: string, phoneLink?: string | null, address?: string | null, copyright?: string | null, contactHeadingLine1?: string | null, contactHeadingLine2?: string | null, scrollText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, socials?: Array<{ __typename: 'SiteSettingsSocials', name: string, url: string, openInNewTab?: boolean | null } | null> | null, footerLinks?: Array<{ __typename: 'SiteSettingsFooterLinks', label: string, url: string } | null> | null } };

export type SiteSettingsConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<SiteSettingsFilter>;
}>;


export type SiteSettingsConnectionQuery = { __typename?: 'Query', siteSettingsConnection: { __typename?: 'SiteSettingsConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'SiteSettingsConnectionEdges', cursor: string, node?: { __typename: 'SiteSettings', id: string, email: string, phone: string, phoneLink?: string | null, address?: string | null, copyright?: string | null, contactHeadingLine1?: string | null, contactHeadingLine2?: string | null, scrollText?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, socials?: Array<{ __typename: 'SiteSettingsSocials', name: string, url: string, openInNewTab?: boolean | null } | null> | null, footerLinks?: Array<{ __typename: 'SiteSettingsFooterLinks', label: string, url: string } | null> | null } | null } | null> | null } };

export type PartnersQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PartnersQuery = { __typename?: 'Query', partners: { __typename: 'Partners', id: string, partnersLabel: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, partners?: Array<{ __typename: 'PartnersPartners', name: string, url?: string | null } | null> | null } };

export type PartnersConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PartnersFilter>;
}>;


export type PartnersConnectionQuery = { __typename?: 'Query', partnersConnection: { __typename?: 'PartnersConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PartnersConnectionEdges', cursor: string, node?: { __typename: 'Partners', id: string, partnersLabel: string, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, partners?: Array<{ __typename: 'PartnersPartners', name: string, url?: string | null } | null> | null } | null } | null> | null } };

export type HomePageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type HomePageQuery = { __typename?: 'Query', homePage: { __typename: 'HomePage', id: string, heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, heroDescription?: string | null, aboutHeading?: string | null, aboutParagraph1?: string | null, aboutParagraph2?: string | null, servicesHeading?: string | null, servicesSubtext?: string | null, servicesButtonText?: string | null, processHeading?: string | null, processSubtext?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, services?: Array<{ __typename: 'HomePageServices', id?: string | null, title: string, description?: string | null } | null> | null, processSteps?: Array<{ __typename: 'HomePageProcessSteps', num?: string | null, title: string, description?: string | null, tags?: Array<string | null> | null } | null> | null } };

export type HomePageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<HomePageFilter>;
}>;


export type HomePageConnectionQuery = { __typename?: 'Query', homePageConnection: { __typename?: 'HomePageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'HomePageConnectionEdges', cursor: string, node?: { __typename: 'HomePage', id: string, heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, heroDescription?: string | null, aboutHeading?: string | null, aboutParagraph1?: string | null, aboutParagraph2?: string | null, servicesHeading?: string | null, servicesSubtext?: string | null, servicesButtonText?: string | null, processHeading?: string | null, processSubtext?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, services?: Array<{ __typename: 'HomePageServices', id?: string | null, title: string, description?: string | null } | null> | null, processSteps?: Array<{ __typename: 'HomePageProcessSteps', num?: string | null, title: string, description?: string | null, tags?: Array<string | null> | null } | null> | null } | null } | null> | null } };

export type TestimonialsPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type TestimonialsPageQuery = { __typename?: 'Query', testimonialsPage: { __typename: 'TestimonialsPage', id: string, heading: string, subtext?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, testimonials?: Array<{ __typename: 'TestimonialsPageTestimonials', quote: string, name: string, role: string, company?: string | null } | null> | null } };

export type TestimonialsPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<TestimonialsPageFilter>;
}>;


export type TestimonialsPageConnectionQuery = { __typename?: 'Query', testimonialsPageConnection: { __typename?: 'TestimonialsPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'TestimonialsPageConnectionEdges', cursor: string, node?: { __typename: 'TestimonialsPage', id: string, heading: string, subtext?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, testimonials?: Array<{ __typename: 'TestimonialsPageTestimonials', quote: string, name: string, role: string, company?: string | null } | null> | null } | null } | null> | null } };

export type AboutPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type AboutPageQuery = { __typename?: 'Query', aboutPage: { __typename: 'AboutPage', id: string, heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, studioImage?: string | null, studioImageAlt?: string | null, introHeading?: string | null, introParagraph1?: string | null, introParagraph2?: string | null, valuesLabel?: string | null, valuesHeading?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, values?: Array<{ __typename: 'AboutPageValues', id?: string | null, title: string, description?: string | null } | null> | null, teamMembers?: Array<{ __typename: 'AboutPageTeamMembers', name: string, role: string, image?: string | null, bio?: string | null, order?: number | null } | null> | null } };

export type AboutPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<AboutPageFilter>;
}>;


export type AboutPageConnectionQuery = { __typename?: 'Query', aboutPageConnection: { __typename?: 'AboutPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'AboutPageConnectionEdges', cursor: string, node?: { __typename: 'AboutPage', id: string, heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, studioImage?: string | null, studioImageAlt?: string | null, introHeading?: string | null, introParagraph1?: string | null, introParagraph2?: string | null, valuesLabel?: string | null, valuesHeading?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, values?: Array<{ __typename: 'AboutPageValues', id?: string | null, title: string, description?: string | null } | null> | null, teamMembers?: Array<{ __typename: 'AboutPageTeamMembers', name: string, role: string, image?: string | null, bio?: string | null, order?: number | null } | null> | null } | null } | null> | null } };

export type ServicesPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ServicesPageQuery = { __typename?: 'Query', servicesPage: { __typename: 'ServicesPage', id: string, heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, categories?: Array<{ __typename: 'ServicesPageCategories', category: string, description?: string | null, items?: Array<string | null> | null } | null> | null } };

export type ServicesPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ServicesPageFilter>;
}>;


export type ServicesPageConnectionQuery = { __typename?: 'Query', servicesPageConnection: { __typename?: 'ServicesPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ServicesPageConnectionEdges', cursor: string, node?: { __typename: 'ServicesPage', id: string, heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, categories?: Array<{ __typename: 'ServicesPageCategories', category: string, description?: string | null, items?: Array<string | null> | null } | null> | null } | null } | null> | null } };

export type ContactPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type ContactPageQuery = { __typename?: 'Query', contactPage: { __typename: 'ContactPage', id: string, heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, heroTitlePunctuation?: string | null, heroDescription?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, trustIndicators?: Array<{ __typename: 'ContactPageTrustIndicators', icon?: string | null, title: string, description?: string | null } | null> | null } };

export type ContactPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<ContactPageFilter>;
}>;


export type ContactPageConnectionQuery = { __typename?: 'Query', contactPageConnection: { __typename?: 'ContactPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'ContactPageConnectionEdges', cursor: string, node?: { __typename: 'ContactPage', id: string, heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, heroTitlePunctuation?: string | null, heroDescription?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, trustIndicators?: Array<{ __typename: 'ContactPageTrustIndicators', icon?: string | null, title: string, description?: string | null } | null> | null } | null } | null> | null } };

export type PricingPageQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PricingPageQuery = { __typename?: 'Query', pricingPage: { __typename: 'PricingPage', id: string, heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, heroSubtext?: string | null, sectionLabel?: string | null, sectionHeading?: string | null, sectionSubtext?: string | null, customLabel?: string | null, customDescription?: string | null, customCtaLabel?: string | null, customCtaHref?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, plans?: Array<{ __typename: 'PricingPagePlans', label?: string | null, name: string, price: string, priceNote?: string | null, delivery?: string | null, tagline?: string | null, featured?: boolean | null, ctaLabel?: string | null, features?: Array<string | null> | null, bestFor?: string | null, revisions?: string | null, ctaLink?: { __typename: 'PricingPagePlansCtaLink', linkType?: string | null, linkValue?: string | null } | null } | null> | null } };

export type PricingPageConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PricingPageFilter>;
}>;


export type PricingPageConnectionQuery = { __typename?: 'Query', pricingPageConnection: { __typename?: 'PricingPageConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PricingPageConnectionEdges', cursor: string, node?: { __typename: 'PricingPage', id: string, heroLabel: string, heroTitleLine1?: string | null, heroTitleLine2?: string | null, heroSubtext?: string | null, sectionLabel?: string | null, sectionHeading?: string | null, sectionSubtext?: string | null, customLabel?: string | null, customDescription?: string | null, customCtaLabel?: string | null, customCtaHref?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string }, plans?: Array<{ __typename: 'PricingPagePlans', label?: string | null, name: string, price: string, priceNote?: string | null, delivery?: string | null, tagline?: string | null, featured?: boolean | null, ctaLabel?: string | null, features?: Array<string | null> | null, bestFor?: string | null, revisions?: string | null, ctaLink?: { __typename: 'PricingPagePlansCtaLink', linkType?: string | null, linkValue?: string | null } | null } | null> | null } | null } | null> | null } };

export const ProjectPartsFragmentDoc = gql`
    fragment ProjectParts on Project {
  __typename
  title
  slug
  category
  techStack
  image
  year
  order
  featuredOnHome
  description
  fullDescription
  gallery
  siteUrl
}
    `;
export const SiteSettingsPartsFragmentDoc = gql`
    fragment SiteSettingsParts on SiteSettings {
  __typename
  email
  phone
  phoneLink
  address
  copyright
  contactHeadingLine1
  contactHeadingLine2
  scrollText
  socials {
    __typename
    name
    url
    openInNewTab
  }
  footerLinks {
    __typename
    label
    url
  }
}
    `;
export const PartnersPartsFragmentDoc = gql`
    fragment PartnersParts on Partners {
  __typename
  partnersLabel
  partners {
    __typename
    name
    url
  }
}
    `;
export const HomePagePartsFragmentDoc = gql`
    fragment HomePageParts on HomePage {
  __typename
  heroLabel
  heroTitleLine1
  heroTitleLine2
  heroDescription
  aboutHeading
  aboutParagraph1
  aboutParagraph2
  servicesHeading
  servicesSubtext
  servicesButtonText
  services {
    __typename
    id
    title
    description
  }
  processHeading
  processSubtext
  processSteps {
    __typename
    num
    title
    description
    tags
  }
}
    `;
export const TestimonialsPagePartsFragmentDoc = gql`
    fragment TestimonialsPageParts on TestimonialsPage {
  __typename
  heading
  subtext
  testimonials {
    __typename
    quote
    name
    role
    company
  }
}
    `;
export const AboutPagePartsFragmentDoc = gql`
    fragment AboutPageParts on AboutPage {
  __typename
  heroLabel
  heroTitleLine1
  heroTitleLine2
  studioImage
  studioImageAlt
  introHeading
  introParagraph1
  introParagraph2
  valuesLabel
  valuesHeading
  values {
    __typename
    id
    title
    description
  }
  teamMembers {
    __typename
    name
    role
    image
    bio
    order
  }
}
    `;
export const ServicesPagePartsFragmentDoc = gql`
    fragment ServicesPageParts on ServicesPage {
  __typename
  heroLabel
  heroTitleLine1
  heroTitleLine2
  categories {
    __typename
    category
    description
    items
  }
}
    `;
export const ContactPagePartsFragmentDoc = gql`
    fragment ContactPageParts on ContactPage {
  __typename
  heroLabel
  heroTitleLine1
  heroTitleLine2
  heroTitlePunctuation
  heroDescription
  trustIndicators {
    __typename
    icon
    title
    description
  }
}
    `;
export const PricingPagePartsFragmentDoc = gql`
    fragment PricingPageParts on PricingPage {
  __typename
  heroLabel
  heroTitleLine1
  heroTitleLine2
  heroSubtext
  sectionLabel
  sectionHeading
  sectionSubtext
  plans {
    __typename
    label
    name
    price
    priceNote
    delivery
    tagline
    featured
    ctaLabel
    ctaLink {
      __typename
      linkType
      linkValue
    }
    features
    bestFor
    revisions
  }
  customLabel
  customDescription
  customCtaLabel
  customCtaHref
}
    `;
export const ProjectDocument = gql`
    query project($relativePath: String!) {
  project(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ProjectParts
  }
}
    ${ProjectPartsFragmentDoc}`;
export const ProjectConnectionDocument = gql`
    query projectConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ProjectFilter) {
  projectConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ProjectParts
      }
    }
  }
}
    ${ProjectPartsFragmentDoc}`;
export const SiteSettingsDocument = gql`
    query siteSettings($relativePath: String!) {
  siteSettings(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...SiteSettingsParts
  }
}
    ${SiteSettingsPartsFragmentDoc}`;
export const SiteSettingsConnectionDocument = gql`
    query siteSettingsConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: SiteSettingsFilter) {
  siteSettingsConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...SiteSettingsParts
      }
    }
  }
}
    ${SiteSettingsPartsFragmentDoc}`;
export const PartnersDocument = gql`
    query partners($relativePath: String!) {
  partners(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PartnersParts
  }
}
    ${PartnersPartsFragmentDoc}`;
export const PartnersConnectionDocument = gql`
    query partnersConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PartnersFilter) {
  partnersConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PartnersParts
      }
    }
  }
}
    ${PartnersPartsFragmentDoc}`;
export const HomePageDocument = gql`
    query homePage($relativePath: String!) {
  homePage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...HomePageParts
  }
}
    ${HomePagePartsFragmentDoc}`;
export const HomePageConnectionDocument = gql`
    query homePageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: HomePageFilter) {
  homePageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...HomePageParts
      }
    }
  }
}
    ${HomePagePartsFragmentDoc}`;
export const TestimonialsPageDocument = gql`
    query testimonialsPage($relativePath: String!) {
  testimonialsPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...TestimonialsPageParts
  }
}
    ${TestimonialsPagePartsFragmentDoc}`;
export const TestimonialsPageConnectionDocument = gql`
    query testimonialsPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: TestimonialsPageFilter) {
  testimonialsPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...TestimonialsPageParts
      }
    }
  }
}
    ${TestimonialsPagePartsFragmentDoc}`;
export const AboutPageDocument = gql`
    query aboutPage($relativePath: String!) {
  aboutPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...AboutPageParts
  }
}
    ${AboutPagePartsFragmentDoc}`;
export const AboutPageConnectionDocument = gql`
    query aboutPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: AboutPageFilter) {
  aboutPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...AboutPageParts
      }
    }
  }
}
    ${AboutPagePartsFragmentDoc}`;
export const ServicesPageDocument = gql`
    query servicesPage($relativePath: String!) {
  servicesPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ServicesPageParts
  }
}
    ${ServicesPagePartsFragmentDoc}`;
export const ServicesPageConnectionDocument = gql`
    query servicesPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ServicesPageFilter) {
  servicesPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ServicesPageParts
      }
    }
  }
}
    ${ServicesPagePartsFragmentDoc}`;
export const ContactPageDocument = gql`
    query contactPage($relativePath: String!) {
  contactPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...ContactPageParts
  }
}
    ${ContactPagePartsFragmentDoc}`;
export const ContactPageConnectionDocument = gql`
    query contactPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: ContactPageFilter) {
  contactPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...ContactPageParts
      }
    }
  }
}
    ${ContactPagePartsFragmentDoc}`;
export const PricingPageDocument = gql`
    query pricingPage($relativePath: String!) {
  pricingPage(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PricingPageParts
  }
}
    ${PricingPagePartsFragmentDoc}`;
export const PricingPageConnectionDocument = gql`
    query pricingPageConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PricingPageFilter) {
  pricingPageConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PricingPageParts
      }
    }
  }
}
    ${PricingPagePartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      project(variables: ProjectQueryVariables, options?: C): Promise<{data: ProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectQueryVariables, query: string}> {
        return requester<{data: ProjectQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectQueryVariables, query: string}, ProjectQueryVariables>(ProjectDocument, variables, options);
      },
    projectConnection(variables?: ProjectConnectionQueryVariables, options?: C): Promise<{data: ProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectConnectionQueryVariables, query: string}> {
        return requester<{data: ProjectConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ProjectConnectionQueryVariables, query: string}, ProjectConnectionQueryVariables>(ProjectConnectionDocument, variables, options);
      },
    siteSettings(variables: SiteSettingsQueryVariables, options?: C): Promise<{data: SiteSettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsQueryVariables, query: string}> {
        return requester<{data: SiteSettingsQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsQueryVariables, query: string}, SiteSettingsQueryVariables>(SiteSettingsDocument, variables, options);
      },
    siteSettingsConnection(variables?: SiteSettingsConnectionQueryVariables, options?: C): Promise<{data: SiteSettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsConnectionQueryVariables, query: string}> {
        return requester<{data: SiteSettingsConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: SiteSettingsConnectionQueryVariables, query: string}, SiteSettingsConnectionQueryVariables>(SiteSettingsConnectionDocument, variables, options);
      },
    partners(variables: PartnersQueryVariables, options?: C): Promise<{data: PartnersQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartnersQueryVariables, query: string}> {
        return requester<{data: PartnersQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartnersQueryVariables, query: string}, PartnersQueryVariables>(PartnersDocument, variables, options);
      },
    partnersConnection(variables?: PartnersConnectionQueryVariables, options?: C): Promise<{data: PartnersConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartnersConnectionQueryVariables, query: string}> {
        return requester<{data: PartnersConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PartnersConnectionQueryVariables, query: string}, PartnersConnectionQueryVariables>(PartnersConnectionDocument, variables, options);
      },
    homePage(variables: HomePageQueryVariables, options?: C): Promise<{data: HomePageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageQueryVariables, query: string}> {
        return requester<{data: HomePageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageQueryVariables, query: string}, HomePageQueryVariables>(HomePageDocument, variables, options);
      },
    homePageConnection(variables?: HomePageConnectionQueryVariables, options?: C): Promise<{data: HomePageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageConnectionQueryVariables, query: string}> {
        return requester<{data: HomePageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: HomePageConnectionQueryVariables, query: string}, HomePageConnectionQueryVariables>(HomePageConnectionDocument, variables, options);
      },
    testimonialsPage(variables: TestimonialsPageQueryVariables, options?: C): Promise<{data: TestimonialsPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsPageQueryVariables, query: string}> {
        return requester<{data: TestimonialsPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsPageQueryVariables, query: string}, TestimonialsPageQueryVariables>(TestimonialsPageDocument, variables, options);
      },
    testimonialsPageConnection(variables?: TestimonialsPageConnectionQueryVariables, options?: C): Promise<{data: TestimonialsPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsPageConnectionQueryVariables, query: string}> {
        return requester<{data: TestimonialsPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: TestimonialsPageConnectionQueryVariables, query: string}, TestimonialsPageConnectionQueryVariables>(TestimonialsPageConnectionDocument, variables, options);
      },
    aboutPage(variables: AboutPageQueryVariables, options?: C): Promise<{data: AboutPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutPageQueryVariables, query: string}> {
        return requester<{data: AboutPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutPageQueryVariables, query: string}, AboutPageQueryVariables>(AboutPageDocument, variables, options);
      },
    aboutPageConnection(variables?: AboutPageConnectionQueryVariables, options?: C): Promise<{data: AboutPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutPageConnectionQueryVariables, query: string}> {
        return requester<{data: AboutPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: AboutPageConnectionQueryVariables, query: string}, AboutPageConnectionQueryVariables>(AboutPageConnectionDocument, variables, options);
      },
    servicesPage(variables: ServicesPageQueryVariables, options?: C): Promise<{data: ServicesPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesPageQueryVariables, query: string}> {
        return requester<{data: ServicesPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesPageQueryVariables, query: string}, ServicesPageQueryVariables>(ServicesPageDocument, variables, options);
      },
    servicesPageConnection(variables?: ServicesPageConnectionQueryVariables, options?: C): Promise<{data: ServicesPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesPageConnectionQueryVariables, query: string}> {
        return requester<{data: ServicesPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ServicesPageConnectionQueryVariables, query: string}, ServicesPageConnectionQueryVariables>(ServicesPageConnectionDocument, variables, options);
      },
    contactPage(variables: ContactPageQueryVariables, options?: C): Promise<{data: ContactPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactPageQueryVariables, query: string}> {
        return requester<{data: ContactPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactPageQueryVariables, query: string}, ContactPageQueryVariables>(ContactPageDocument, variables, options);
      },
    contactPageConnection(variables?: ContactPageConnectionQueryVariables, options?: C): Promise<{data: ContactPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactPageConnectionQueryVariables, query: string}> {
        return requester<{data: ContactPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: ContactPageConnectionQueryVariables, query: string}, ContactPageConnectionQueryVariables>(ContactPageConnectionDocument, variables, options);
      },
    pricingPage(variables: PricingPageQueryVariables, options?: C): Promise<{data: PricingPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricingPageQueryVariables, query: string}> {
        return requester<{data: PricingPageQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricingPageQueryVariables, query: string}, PricingPageQueryVariables>(PricingPageDocument, variables, options);
      },
    pricingPageConnection(variables?: PricingPageConnectionQueryVariables, options?: C): Promise<{data: PricingPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricingPageConnectionQueryVariables, query: string}> {
        return requester<{data: PricingPageConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PricingPageConnectionQueryVariables, query: string}, PricingPageConnectionQueryVariables>(PricingPageConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  